### ISSUE TITLE
Auto-Hide Livestreams from Subscription Feed

### ISSUE THREAD

**Issue by TakotoLuke** [OsaSoft/youtube-better-subscriptions#117] opened 2022-06-03 13:43 UTC
Would there be a possibility of having a feature for automatically hiding currently airing live-streams from the subscription feed?

I find when following a ton of channels, sometimes they end up creating a really long/cumbersome list at the top of the subscription feed. No worries if not possible!

Either way, great work on this!

**Comment by grandslammer** [comment] 2022-06-23 22:25
Related to #36 and #97

**Comment by OsaSoft** [comment] 2023-02-12 14:28
Duplicate of #97

**Closed by OsaSoft** 2023-02-12 14:28 UTC
