### ISSUE TITLE
Version 19 broke all funtunallity 

### ISSUE THREAD

**Issue by HauptlingHD** [OsaSoft/youtube-better-subscriptions#167] opened 2023-10-03 15:09 UTC
Version 19.0 broke all functionality. I just updated to 19.0 and the extension stopped working. There is no UI, and all videos that were marked as washed are unhidden again. Browser restarts do not help.

(Brave: 1.58.135 Chromium: 117.0.5938.140)

**Comment by OsaSoft** [comment] 2023-10-03 15:18
Duplicate of #165, already fixed in 0.19.1, which is currently pending approval by Chrome web store

**Closed by OsaSoft** 2023-10-03 15:18 UTC
