### ISSUE TITLE
"Shorts" videos have stopped being marked as played

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#109] opened 2022-03-23 19:32 UTC
- Issue only affecting YouTube Shorts videos
- Only started happening in the last day or 2 (YouTube update I suspect)

**Comment by HidyHo** [comment] 2022-03-26 13:55
After opening Shorts, if you add "&loop=1" to the end of the link, the video will revert to "standard" format with a progress bar and the video will be removed from the subscription.

I came here to ask the developer to consider adding this functionality to the extension.

**Comment by HidyHo** [comment] 2022-03-28 13:59
Found Chrome extension called "Youtube-shorts block" that take of shorts by reverting to "standard"format.

**Comment by OsaSoft** [comment] 2022-04-10 18:02
hey and thanks for raising this issue. Yeah, its caused by Youtube using a new different url for shorts. Should be a simple fix, i hope i can get to it soon

**Comment by OsaSoft** [comment] 2023-02-12 12:13
resolved by #130

**Closed by OsaSoft** 2023-02-12 12:13 UTC
Labels: bug
