### ISSUE TITLE
Extension spitting a bunch of errors and not entirely working

### ISSUE THREAD

**Issue by terrygonguet** [OsaSoft/youtube-better-subscriptions#102] opened 2021-09-19 22:24 UTC
Just installed the extension and the hiding of watched videos in the home tab doesn't seem to work. At first nothing worked but the hiding seems ok in the subscriptions.

<details>
<summary>In the home tab, the extension throws these errors every time it tries to check:</summary>

```
[YT-Better-Subs] Removing watched from feed and adding overlay
util.js:16 [YT-Better-Subs] ERROR!  Cannot read properties of null (reading 'split')
    logError @ util.js:16
    (anonymous) @ subs.js:148
    setInterval (async)
    (anonymous) @ subs.js:143
    Promise.then (async)
    initSubs @ subs.js:129
    handlePageChange @ pageHandler.js:35
    (anonymous) @ pageHandler.js:60
    (anonymous) @ pageHandler.js:57
    attributes (async)
    (anonymous) @ desktop_polymer.js:22659
    (anonymous) @ web-animations-next-lite.min.js:96
    requestAnimationFrame (async)
    window.requestAnimationFrame @ web-animations-next-lite.min.js:96
    (anonymous) @ desktop_polymer.js:11868
    setTimeout (async)
    asyncFrame @ desktop_polymer.js:11868
    finish @ desktop_polymer.js:22659
    finishNavigation_ @ desktop_polymer.js:22371
    (anonymous) @ desktop_polymer.js:22376
    e.JSC$30357_onFulfilled @ desktop_polymer.js:1026
    aga @ desktop_polymer.js:1036
    Xfa @ desktop_polymer.js:1036
    ji.JSC$30362_executeCallbacks_ @ desktop_polymer.js:1035
    Xea @ desktop_polymer.js:874
    Promise.then (async)
    sh @ desktop_polymer.js:874
    th @ desktop_polymer.js:873
    Yfa @ desktop_polymer.js:1033
    ii @ desktop_polymer.js:1031
    ji.unblockAndFulfill_ @ desktop_polymer.js:1029
    l @ desktop_polymer.js:1032
    Promise.then (async)
    $fa @ desktop_polymer.js:1033
    Ofa @ desktop_polymer.js:1032
    ii @ desktop_polymer.js:1031
    (anonymous) @ desktop_polymer.js:1005
    (anonymous) @ desktop_polymer.js:2711
    Ca @ desktop_polymer.js:53
    next @ desktop_polymer.js:55
    h @ desktop_polymer.js:339
    Promise.then (async)
    m @ desktop_polymer.js:341
    (anonymous) @ desktop_polymer.js:342
    A @ desktop_polymer.js:339
    (anonymous) @ desktop_polymer.js:2711
    ji @ desktop_polymer.js:1005
    Mp @ desktop_polymer.js:2711
    Uq @ desktop_polymer.js:2888
    navigate @ desktop_polymer.js:22504
    handleNavigate @ desktop_polymer.js:22381
    onYtNavigate_ @ desktop_polymer.js:22379
    (anonymous) @ desktop_polymer.js:3629
    xb @ webcomponents-sd.js:39
    k.dispatchEvent @ webcomponents-sd.js:105
    a.fire @ desktop_polymer.js:4191
    (anonymous) @ desktop_polymer.js:12175
    sla @ desktop_polymer.js:1724
    handleClick_ @ desktop_polymer.js:12175
    onEndpointClick_ @ desktop_polymer.js:12171
    (anonymous) @ desktop_polymer.js:3629
util.js:17 TypeError: Cannot read properties of null (reading 'split')
    at getVideoIdFromUrl (subs.js:106)
    at getVideoId (subs.js:110)
    at removeWatchedAndAddButton (subs-ui.js:255)
    at subs.js:146
```

</details>

<details>
<summary>And it throws that every second:</summary>

```
content.js:67 Uncaught RangeError: Invalid time value
    at updateLabel (content.js:67)
    at content.js:95
updateLabel @ content.js:67
(anonymous) @ content.js:95
setInterval (async)
(anonymous) @ content.js:93
```

</details>

I'm using latest Vivaldi on Ubuntu 20.

I'm also using a few other extensions to make Youtube bearable. It seemed to work better when I disabled some but not any more.

I use Enhancer for Youtube, Sponsor Block, Youtube Ends At and a few custom styles.

**Comment by OsaSoft** [comment] 2021-09-20 09:38
hmm that seems like it thinks its on a video page when its on the home page and tries to get the video ID.
Does it behave the same way if you directly enter https//youtube.com in a new tab or if you refresh the page?

As for the second error, there is no "content.js" in this addon, so i think that might be caused by something else?

**Comment by terrygonguet** [comment] 2021-09-20 09:49
I tried a bunch of things and yes, it does that no matter how I end up on the front page or subscriptions.

Also yes indeed, apparently the second error is just Youtube being confused at my attemps at making the app ~~not~~ less user hostile.

Sadly I can't use this extension like that so I wrote a small userscript to hide watched videos. Good luck though.

**Comment by OsaSoft** [comment] 2021-09-20 09:54
I see. It might be some specific quirk with Vivaldi. Ill try to install it and test it out.

**Comment by tabrown97** [comment] 2021-09-20 11:16
I am using the latest version of Chrome (93.0.4577.82) and I have the same problem.  I used to have "Improve YouTube!" extension installed, but I remove all extensions related to YouTube and just reinstalled this one and the problem remains.  The "mark as watched" button has disappeared just from the home page.

**Comment by OsaSoft** [comment] 2021-09-20 11:31
I see. Can you put up a screenshot of the YT homepage? This smells like YT is rolling out some updated homepage to some people which breaks this functionality, as Youtube likes to do 😅

**Comment by tabrown97** [comment] 2021-09-20 12:01
![Youtube_Home_Page](https://user-images.githubusercontent.com/74570035/133998655-105c5b5e-0baa-4d6f-a70a-c1c01d92d279.JPG)
I do have a YouTube Premium account so that may change my homepage.

**Comment by OsaSoft** [comment] 2021-09-20 12:05
I also have Preminum, so that shouldnt be an issue. It does look pretty much the same as on my side

can you enable debug logging in the extension settings page and post the full logs? 
![image](https://user-images.githubusercontent.com/8895463/133999254-bfde2bc3-ed43-4e8e-b1d2-98ffcc33540b.png)

**Comment by tabrown97** [comment] 2021-09-20 12:13
I'm having trouble locating how to grab the logs.

**Comment by OsaSoft** [comment] 2021-09-20 21:50
Ok ive replicated the issue in Chrome. Seems to be something specific to the "special" enhanced version of YT that is served to Chrome. Ill try to find a fix

**Comment by OsaSoft** [comment] 2023-02-12 14:04
I believe this has been resolved by other fixes/changes. Closing

**Closed by OsaSoft** 2023-02-12 14:04 UTC
Labels: bug
