### ISSUE TITLE
No videos being hidden at all.

### ISSUE THREAD

**Issue by surfarcher** [OsaSoft/youtube-better-subscriptions#75] opened 2020-03-30 23:58 UTC
Watched. Mark as watch. All videos just stopped being hidden.

It's like the plugin isn't even installed :'(

**Comment by GentlePuppet** [comment] 2020-03-31 05:08
It seems like a youtube update broke the extension.

**Comment by surfarcher** [comment] 2020-03-31 05:16
I figured it was probably that. Seems more likely than a Chrome update (which was my second guess).

**Comment by idt1201** [comment] 2020-03-31 05:32
Same here was working 12 hours ago! suddenly stopped.

**Comment by GarrettRobinson** [comment] 2020-03-31 07:08
Submitted a pull request with a verified fix here https://github.com/OsaSoft/youtube-better-subscriptions/pull/76#issue-396118934

If you'd like to make it work yourself until the update is pushed here are the steps:

- download the .zip of the extension and extract somewhere
- change line 252 of subs-ui.js to let dismissableDiv = item.**firstElementChild**;
- load unpacked extension into browser

**Comment by OsaSoft** [comment] 2020-03-31 07:30
hey all! Sorry, been a little overloaded with work lately and since I wasnt able to reproduce the issue immediately had to put it off for a bit.
It seems indeed like a YT update that is slowly getting rolled out to people, which is pretty annoying, since a full fix will likely have to include a compatibility layer, so it works both for people before and after the update.

@GarrettRobinson awesome! Ill take a look asap

**Comment by OsaSoft** [comment] 2020-03-31 09:35
Resolved with #76

**Closed by OsaSoft** 2020-03-31 09:35 UTC
Labels: bug

**Comment by OsaSoft** [comment] 2020-03-31 09:52
Firefox version is up, if youd like to speed up the update, go to about:addons, click the wheel on top right and select "update addons"
