### ISSUE TITLE
New version seems to have stopped funtioning.

### ISSUE THREAD

**Issue by isgdre** [OsaSoft/youtube-better-subscriptions#168] opened 2023-10-03 17:03 UTC
0.19.0 no longer works at all in YouTube.
The extension is installed and enabled but the icon doesn't show up by the youtube search.
It doesn't affect the youtube.com/feed/subscriptions or channel's individual videos page.

Is there something I need to do to reenable it?

**Comment by OsaSoft** [comment] 2023-10-03 17:05
Duplicate of #165 #167  , already fixed in 0.19.1, which is currently pending approval by Chrome web store

**Closed by OsaSoft** 2023-10-03 17:05 UTC
