### ISSUE TITLE
Titles are not hidden

### ISSUE THREAD

**Issue by DavidDrezen** [OsaSoft/youtube-better-subscriptions#47] opened 2018-08-24 18:01 UTC
When there is no remaining videos to see in a category, the title should disappear. 

Currently I have this :

![capture](https://user-images.githubusercontent.com/1626386/44599986-3fcd6500-a7d8-11e8-87c4-737855318438.JPG)

**Comment by OsaSoft** [comment] 2018-08-24 18:47
Duplicate of #28

**Closed by OsaSoft** 2018-08-24 18:47 UTC
