### ISSUE TITLE
[feature request] Hide premieres

### ISSUE THREAD

**Issue by Aslanex** [OsaSoft/youtube-better-subscriptions#71] opened 2020-02-13 12:12 UTC
How about an option to hide all unreleased premieres, while the video still showed up after being published?

**Comment by OsaSoft** [comment] 2020-02-14 15:24
duplicate of #68

**Comment by OsaSoft** [comment] 2020-02-14 15:25
and yes, this is definitely something Ive got in the pipeline, though god knows when Ill be able to get around to actually implement it

**Closed by OsaSoft** 2020-02-14 15:25 UTC
Labels: duplicate
