### ISSUE TITLE
Extra options to add

### ISSUE THREAD

**Issue by Eriklinuxuser** [OsaSoft/youtube-better-subscriptions#119] opened 2022-07-25 06:01 UTC
I don't have a bug to report but i wish to see this in a new upgrade:
On the subscription page of youtube i want to see a option to stop searching for new videos, it keeps adding videos from months or even years ago and then lists/displays them.
I wish to have a clean feed/subscription page and only see new videos being released but it slows down the browser to much if it keeps searching all channels years and years back.
Perhaps a option on the options pages to allow the extension to search on this specific page (subscriptions) for a set period ie. 1 month back, 2, 3 months back or 1 year.....

**Comment by OsaSoft** [comment] 2023-02-12 14:26
duplicate of #63

**Closed by OsaSoft** 2023-02-12 14:26 UTC
