### ISSUE TITLE
Publish extension via Github Actions

### ISSUE THREAD

**Issue by mocanew** [OsaSoft/youtube-better-subscriptions#158] opened 2023-09-18 04:18 UTC
If Github Actions were used to publish the extension, this would allow multiple maintainers, as anyone with push rights on the master branch could publish the extension. Also, it would reduce the time needed to maintain this repo.

Here's an excellent article detailing the steps taken for such an approach: https://dev.to/cardinalby/webextension-deployment-and-publishing-using-github-actions-522o

I wish to create a PR on this by the end of the week.

**Comment by OsaSoft** [comment] 2023-09-20 15:56
Yes, this has been on the todo list for quite a while :sweat:, so partial duplicate of #61, since that is only related to firefox, i take it you also mean the chrome webstore

**Closed** 2023-10-02 11:57 UTC
